//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point LocationAndSizeForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["LocationAndSizeForm_Location"]));
            }
            set {
                this["LocationAndSizeForm_Location"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point PasswordsForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["PasswordsForm_Location"]));
            }
            set {
                this["PasswordsForm_Location"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point SendCommandsForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["SendCommandsForm_Location"]));
            }
            set {
                this["SendCommandsForm_Location"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideMinimized {
            get {
                return ((bool)(this["HideMinimized"]));
            }
            set {
                this["HideMinimized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoTrackReminder {
            get {
                return ((bool)(this["AutoTrackReminder"]));
            }
            set {
                this["AutoTrackReminder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int AutoTrackReminderIntervalSeconds {
            get {
                return ((int)(this["AutoTrackReminderIntervalSeconds"]));
            }
            set {
                this["AutoTrackReminderIntervalSeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point WindowsTrackingForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["WindowsTrackingForm_Location"]));
            }
            set {
                this["WindowsTrackingForm_Location"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%SystemRoot%\\System32\\ssText3d.scr")]
        public string ScreenSaverPath {
            get {
                return ((string)(this["ScreenSaverPath"]));
            }
            set {
                this["ScreenSaverPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://your.proxy:8080")]
        public string DownloaderForm_Proxy {
            get {
                return ((string)(this["DownloaderForm_Proxy"]));
            }
            set {
                this["DownloaderForm_Proxy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloaderForm_Username {
            get {
                return ((string)(this["DownloaderForm_Username"]));
            }
            set {
                this["DownloaderForm_Username"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloaderForm_LocalPath {
            get {
                return ((string)(this["DownloaderForm_LocalPath"]));
            }
            set {
                this["DownloaderForm_LocalPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainForm_LogRefresh {
            get {
                return ((bool)(this["MainForm_LogRefresh"]));
            }
            set {
                this["MainForm_LogRefresh"] = value;
            }
        }
    }
}
